server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
